using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Configuration;
namespace TEPL.QMS.Common.Constants
{
    public static class QMSConstants
    {
        public static string DBCon = Convert.ToString(ConfigurationManager.ConnectionStrings["DBCon"]);
        public static string SiteType = Convert.ToString(ConfigurationManager.AppSettings["SiteType"]);
        public static string SiteName = Convert.ToString(ConfigurationManager.AppSettings["SiteName"]);
        public static string LDAPPath = Convert.ToString(ConfigurationManager.AppSettings["LDAPPath"]);
        public static string WebSiteURL = Convert.ToString(ConfigurationManager.AppSettings["WebSiteURL"]);
        public static string ViewerURL = Convert.ToString(ConfigurationManager.AppSettings["ViewerURL"]);
        public static string SMTPPORT = Convert.ToString(ConfigurationManager.AppSettings["SMTPPORT"]);
        public static string SMTPHOST = Convert.ToString(ConfigurationManager.AppSettings["SMTPHOST"]);
        public static string EmailUserName = Convert.ToString(ConfigurationManager.AppSettings["EmailUserName"]);
        public static string EmailPassword = Convert.ToString(ConfigurationManager.AppSettings["EmailPassword"]);
        public static string EmailFrom = Convert.ToString(ConfigurationManager.AppSettings["EmailFrom"]);
        public static string ServiceAccountName = Convert.ToString(ConfigurationManager.AppSettings["ServiceAccountName"]);
        public static string ServiceAccountPassword = Convert.ToString(ConfigurationManager.AppSettings["ServiceAccountPassword"]);
        public static string CompanyCode = Convert.ToString(ConfigurationManager.AppSettings["CompanyCode"]);
        public static string LoginRegEx = Convert.ToString(ConfigurationManager.AppSettings["LoginRegEx"]);
        public static string LogPath = Convert.ToString(ConfigurationManager.AppSettings["LogPath"]);
        public static string TempFolder = Convert.ToString(ConfigurationManager.AppSettings["TempFolder"]);
        public static string StoragePath = Convert.ToString(ConfigurationManager.AppSettings["StoragePath"]);
        public static string BackUpPath = Convert.ToString(ConfigurationManager.AppSettings["BackUpPath"]);
        public static string HistoryPath = Convert.ToString(ConfigurationManager.AppSettings["HistoryPath"]);
        public static string HistoryBackUpPath = Convert.ToString(ConfigurationManager.AppSettings["HistoryBackUpPath"]);
        public static string DraftFolder = Convert.ToString(ConfigurationManager.AppSettings["DraftFolder"]);
        public static string PublishedFolder = Convert.ToString(ConfigurationManager.AppSettings["PublishedFolder"]);
        public static string EditableFolder = Convert.ToString(ConfigurationManager.AppSettings["EditableFolder"]);
        public static string ReadableFolder = Convert.ToString(ConfigurationManager.AppSettings["ReadableFolder"]);
        public static string TemplateFolder = Convert.ToString(ConfigurationManager.AppSettings["TemplateFolder"]);
        public static string ExtDocumentFolder = Convert.ToString(ConfigurationManager.AppSettings["ExtDocumentFolder"]);
        public static string EncryptionKey = Convert.ToString(ConfigurationManager.AppSettings["EncryptionKey"]);
        public static Guid WorkflowID = Guid.Parse(ConfigurationManager.AppSettings["WorkflowID"]);
        public static Guid PrintWorkflowID = Guid.Parse(ConfigurationManager.AppSettings["PrintWorkflowID"]);
        public static string QMSHeadEmail = Convert.ToString(ConfigurationManager.AppSettings["QMSHeadEmail"]);
        public static string AuthCookieName = Convert.ToString(ConfigurationManager.AppSettings["AuthCookieName"]);

        public const string LoggedInUserID = "LoggedInUserID";
        public const string LoggedInUserDisplayName = "LoggedInUserDisplayName";
        public const string LoggedInUserProjects = "LoggedInUserProjects";
        public const string LoggedInUserRoles = "LoggedInUserRoles";
        

        //StoredProcedures
        public static string spGenerateDocumentNo = "spGenerateDocumentNo";
        public static string spGenerateDocumentNoLevel1 = "spGenerateDocumentNoLevel1";
        public static string spGetDocumentNumbers = "spGetDocumentNumbers";
        public static string spGetDocumentLevel = "spGetDocumentLevel";
        public static string spDocumentUpdate = "spDocumentUpdate";
        public static string spDocumentUpdatePublished = "spDocumentUpdatePublished";
        public static string spDocumentDescriptionUpdate = "spDocumentDescriptionUpdate";
        public static string spDocumentVersionUpdate = "spDocumentVersionUpdate";
        public static string spGetRequestedDocuments = "spGetRequestedDocuments";
        public static string spGetApprovedPrintRequests = "spGetApprovedPrintRequests";
        public static string spGetDocumentDetailsByID = "spGetDocumentDetailsByID";
        public static string spGetPrintRequestDetailsByID = "spGetPrintRequestDetailsByID";
        public static string spGetPublishedDocuments = "spGetPublishedDocuments";
        public static string spGetPublishedDocuments_ServerSide = "spGetPublishedDocuments_ServerSide";
        public static string spGetArchivedDocuments = "spGetArchivedDocuments";
        public static string spGetPublishedDocumentDetailsByID = "spGetPublishedDocumentDetailsByID";
        public static string spGetPublishedDocumentHistoryByID = "spGetPublishedDocumentHistoryByID";
        public static string spGetPublishedDocumentHistoryDetailsByID = "spGetPublishedDocumentHistoryDetailsByID";
        public static string spGetDocumentDetailsByNo = "spGetDocumentDetailsByNo";
        public static string spGetDocumentDetailsForPrintRequest = "spGetDocumentDetailsForPrintRequest";
        public static string spGetApprovalPendingDocuments = "spGetApprovalPendingDocuments";
        public static string spGetApprovedDocuments = "spGetApprovedDocuments";
        public static string spGetDraftDocuments = "spGetDraftDocuments";
        public static string spDocumentPublish = "spDocumentPublish";
        public static string spGetDepartments = "spGetDepartments";
        public static string spGetActiveLocations = "spGetActiveLocations";
        public static string spGetActiveDepartments = "spGetActiveDepartments";
        public static string spGetActiveFunctions = "spGetActiveFunctions";
        public static string spGetSectionsForDept = "spGetSectionsForDept";
        public static string spGetProjectTypes = "spGetProjectTypes";
        public static string spGetProjects = "spGetProjects";
        public static string spGetDocumentCategories = "spGetDocumentCategories";
        public static string spGetAllDocumentCategories = "spGetAllDocumentCategories";
        public static string spGetTemplateDocument = "spGetTemplateDocument";
        public static string spAddTemplateDocument = "spAddTemplateDocument";
        public static string spUpdateTemplateDocument = "spUpdateTemplateDocument";
        public static string spGetLoggedInUserRoles = "spGetLoggedInUserRoles";
        public static string spGetConfigValue = "spGetConfigValue";
        public static string spGetTaskSchedules = "spGetTaskSchedules";
        public static string spInsertUserDetails = "spInsertUserDetails";
        public static string spGetUserDetails = "spGetUserDetails";
        public static string spGetUserDetailsByID = "spGetUserDetailsByID";
        public static string spGetUserEmailByID = "spGetUserEmailByID";
        public static string spSearchUsers = "spSearchUsers";
        public static string spSearchProjectUsers = "spSearchProjectUsers";
        public static string spGetProjectUsers = "spGetProjectUsers";
        public static string spAddUserToProject = "spAddUserToProject";
        public static string spDeleteUserFromProject = "spDeleteUserFromProject";
        public static string spAddDepartment = "spAddDepartment";
        public static string spUpdateDepartment = "spUpdateDepartment";
        public static string spDeleteDepartment = "spDeleteDepartment";
        //public static string spAddSection = "spAddSection";
        public static string spAddDocumentCategory = "spAddDocumentCategory";
        public static string spUpdateDocumentCategory = "spUpdateDocumentCategory";
        public static string spDeleteDocumentCategory = "spDeleteDocumentCategory";
        public static string spGetDocumentApprovers = "spGetDocumentApprovers";
        public static string spGetUsers = "spGetUsers";
        public static string spAddUser = "spAddUser";
        public static string spDeleteUser = "spDeleteUser";
        public static string spUpdateUser = "spUpdateUser";
        public static string spGetAllSections = "spGetAllSections";
        public static string spAddSection = "spAddSection";
        public static string spUpdateSection = "spUpdateSection";
        public static string spDeleteSection = "spDeleteSection";
        public static string spAddProject = "spAddProject";
        public static string spUpdateProject = "spUpdateProject";
        public static string spUpdateMultipleApprovers = "spUpdateMultipleApprovers";
        public static string spDeleteDocument = "spDeleteDocument";
        public static string spDeleteArchivedDocument = "spDeleteArchivedDocument";
        public static string spArchiveDocument = "spArchiveDocument";
        public static string spArchivePendingDocument = "spArchivePendingDocument";
        public static string spGetAllExternalDocuments = "spGetAllExternalDocuments";
        public static string spGetExternalDocumentSeqNumber = "spGetExternalDocumentSeqNumber";
        public static string spGetExternalDocumentDetailsForID = "spGetExternalDocumentDetailsForID";
        public static string spIsExternalDocumentExists = "spIsExternalDocumentExists";
        public static string spInsertExternalDocument = "spInsertExternalDocument";
        public static string spUpdateExternalDocument = "spUpdateExternalDocument";
        public static string spDeleteExternalDocument = "spDeleteExternalDocument";
        public static string spDeleteTemplate = "spDeleteTemplate";
        public static string spUpdateTemplate = "spUpdateTemplate";
        public static string spAddExternalCategory = "spAddExternalCategory";
        public static string spDeleteExternalCategory = "spDeleteExternalCategory";
        public static string spGetExternalCategories = "spGetExternalCategories";
        public static string spGetActiveExternalCategories = "spGetActiveExternalCategories";
        public static string spUpdateExternalCategory = "spUpdateExternalCategory";
        public static string spAddExternalSubCategory = "spAddExternalSubCategory";
        public static string spDeleteExternalSubCategory = "spDeleteExternalSubCategory";
        public static string spGetExternalSubCategories = "spGetExternalSubCategories";
        public static string spGetExternalSubCategoriesForCategory = "spGetExternalSubCategoriesForCategory";
        public static string spUpdateExternalSubCategory = "spUpdateExternalSubCategory";
        public static string spUpdateDocumentNo = "spUpdateDocumentNo";
        public static string spGetUserApprovalItemsForAMID = "spGetUserApprovalItemsForAMID";
        public static string spValidateDocumentNumber = "spValidateDocumentNumber";
        public static string spCreatePrintRequest = "spCreatePrintRequest";
        public static string spAddFunction = "spAddFunction";
        public static string spUpdateFunction = "spUpdateFunction";
        public static string spDeleteFunction = "spDeleteFunction"; 
        public static string spGetFunctions = "spGetFunctions";
        public static string spAddLocation = "spAddLocation";
        public static string spUpdateLocation = "spUpdateLocation";
        public static string spDeleteLocation = "spDeleteLocation";
        public static string spGetLocation = "spGetLocation";
        public static string spGetAchievedDocumentDetailsByID = "spGetAchievedDocumentDetailsByID";
    }
}
